packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - bufferutil
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
  - utf-8-validate
