/**
 * 统一错误码枚举(前后端共享，脚手架版精简)
 */
export enum ErrorCode {
  // 认证
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_VERIFICATION_CODE = 'AUTH_INVALID_VERIFICATION_CODE',
  AUTH_VERIFICATION_CODE_EXPIRED = 'AUTH_VERIFICATION_CODE_EXPIRED',
  AUTH_EMAIL_ALREADY_TAKEN = 'AUTH_EMAIL_ALREADY_TAKEN',
  AUTH_EMAIL_ALREADY_VERIFIED = 'AUTH_EMAIL_ALREADY_VERIFIED',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',

  // 通用
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // 用户/管理员
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  ADMIN_INVALID_PASSWORD = 'ADMIN_INVALID_PASSWORD',

  // RBAC
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  MENU_NOT_FOUND = 'MENU_NOT_FOUND',

  // Settings
  SETTINGS_INVALID_JSON = 'SETTINGS_INVALID_JSON',
  SETTINGS_TYPE_MISMATCH = 'SETTINGS_TYPE_MISMATCH',
  SETTINGS_JSON_EXPECTED_OBJECT_OR_ARRAY = 'SETTINGS_JSON_EXPECTED_OBJECT_OR_ARRAY',
  SETTINGS_NOT_FOUND = 'SETTINGS_NOT_FOUND',

  // Wallet
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_INSUFFICIENT_BALANCE = 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_INSUFFICIENT_FROZEN_BALANCE = 'WALLET_INSUFFICIENT_FROZEN_BALANCE',
  WALLET_ASSET_NOT_FOUND = 'WALLET_ASSET_NOT_FOUND',
  WALLET_ASSET_TYPE_NOT_FOUND = 'WALLET_ASSET_TYPE_NOT_FOUND',
  WALLET_INVALID_DATE_RANGE = 'WALLET_INVALID_DATE_RANGE',
  WALLET_SNAPSHOT_INVALID_DATE_RANGE = 'WALLET_SNAPSHOT_INVALID_DATE_RANGE',
  WALLET_TRANSACTION_FAILED = 'WALLET_TRANSACTION_FAILED',

  // Payment
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_RECHARGE_PACKAGE_NOT_FOUND = 'PAYMENT_RECHARGE_PACKAGE_NOT_FOUND',
  PAYMENT_RECHARGE_PACKAGE_CURRENCY_MISMATCH = 'PAYMENT_RECHARGE_PACKAGE_CURRENCY_MISMATCH',
  PAYMENT_RECHARGE_PACKAGE_PRICE_MISMATCH = 'PAYMENT_RECHARGE_PACKAGE_PRICE_MISMATCH',
  PAYMENT_WITHDRAW_FAILED = 'PAYMENT_WITHDRAW_FAILED',

  // Payment Center (Merchant)
  PAYMENT_SIGNATURE_INVALID = 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_SIGNATURE_MISSING = 'PAYMENT_SIGNATURE_MISSING',
  PAYMENT_REQUEST_TIMEOUT = 'PAYMENT_REQUEST_TIMEOUT',
  PAYMENT_ORDER_NOT_FOUND = 'PAYMENT_ORDER_NOT_FOUND',
  PAYMENT_ORDER_ALREADY_PROCESSED = 'PAYMENT_ORDER_ALREADY_PROCESSED',
  PAYMENT_INVALID_AMOUNT = 'PAYMENT_INVALID_AMOUNT',
  PAYMENT_MERCHANT_NOT_FOUND = 'PAYMENT_MERCHANT_NOT_FOUND',
  PAYMENT_MERCHANT_CONFIG_MISSING = 'PAYMENT_MERCHANT_CONFIG_MISSING',
  PAYMENT_FORBIDDEN = 'PAYMENT_FORBIDDEN',
  PAYMENT_TOKEN_INVALID = 'PAYMENT_TOKEN_INVALID',
  PAYMENT_TOKEN_EXPIRED = 'PAYMENT_TOKEN_EXPIRED',
  PAYMENT_GATEWAY_BUSY = 'PAYMENT_GATEWAY_BUSY',
  PAYMENT_CALLBACK_FAILED = 'PAYMENT_CALLBACK_FAILED',
  /** 支付金额与商户期望金额不匹配 */
  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',

  // External Payment (外部商户支付)
  /** 外部支付签名验证失败 */
  EXTERNAL_PAYMENT_INVALID_SIGNATURE = 'EXTERNAL_PAYMENT_INVALID_SIGNATURE',
  /** 外部支付时间戳过期 */
  EXTERNAL_PAYMENT_TIMESTAMP_EXPIRED = 'EXTERNAL_PAYMENT_TIMESTAMP_EXPIRED',
  /** 外部支付商户不存在 */
  EXTERNAL_PAYMENT_MERCHANT_NOT_FOUND = 'EXTERNAL_PAYMENT_MERCHANT_NOT_FOUND',
  /** 外部支付商户已禁用 */
  EXTERNAL_PAYMENT_MERCHANT_DISABLED = 'EXTERNAL_PAYMENT_MERCHANT_DISABLED',
  /** 外部支付订单号重复 */
  EXTERNAL_PAYMENT_DUPLICATE_ORDER = 'EXTERNAL_PAYMENT_DUPLICATE_ORDER',
  /** 外部支付订单不存在 */
  EXTERNAL_PAYMENT_ORDER_NOT_FOUND = 'EXTERNAL_PAYMENT_ORDER_NOT_FOUND',

  // AI
  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',
  AI_PROVIDER_NOT_FOUND = 'AI_PROVIDER_NOT_FOUND',
  AI_NO_ACTIVE_KEY = 'AI_NO_ACTIVE_KEY',
  PAYMENT_INITIATION_FAILED = 'PAYMENT_INITIATION_FAILED',
  PAYMENT_ORDER_ASSET_INFO_MISSING = 'PAYMENT_ORDER_ASSET_INFO_MISSING',
  PAYMENT_THIRD_PARTY_ERROR = 'PAYMENT_THIRD_PARTY_ERROR',
  PAYMENT_INVALID_AMOUNT_FORMAT = 'PAYMENT_INVALID_AMOUNT_FORMAT',

  // Email
  EMAIL_TEST_ONLY = 'EMAIL_TEST_ONLY',

  // Wallet (extended)
  WALLET_TRANSFER_INVALID_AMOUNT = 'WALLET_TRANSFER_INVALID_AMOUNT',
  WALLET_TEST_ROLLBACK = 'WALLET_TEST_ROLLBACK',
}
